version: '3.9'
services:
  app:
    build: .
    container_name: nodejs_service
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    env_file: .env
    environment:
      - PORT=${PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - postgres
    volumes:
      - type: bind
        source: ./src
        target: /app/src
      - /app/node_modules
    restart: always

  postgres:
    build: ./db/
    container_name: postgres_container
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
