version: '3.9'
services:
  app:
    container_name: nodejs-service
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - ignore:/app/node_modules/
    networks:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_PASSWORD:-rest}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: postgres

  postgres:
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_PASSWORD:-rest}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - postgres
    build: ./db/

networks:
  postgres:
    driver: bridge

volumes:
  ignore:
  postgres:
